GET https://uom3hqkkql.execute-api.us-east-1.amazonaws.com/dev/9e3adef2

###
POST https://uom3hqkkql.execute-api.us-east-1.amazonaws.com/dev/shorten
Content-Type: application/json

{
    "url": "https://www.youtube.com"
}

###
OPTIONS https://uom3hqkkql.execute-api.us-east-1.amazonaws.com/dev/shorten
